# Generated by Django 5.0.4 on 2024-05-19 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directionName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinceName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('districtName', models.CharField(max_length=100)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.province')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wardName', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.district')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.BigIntegerField()),
                ('square', models.FloatField()),
                ('description', models.TextField()),
                ('postTime', models.DateTimeField()),
                ('addressDetail', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
                ('image', models.ImageField(upload_to='static/')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.account')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.direction')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.district')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.province')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.ward')),
            ],
        ),
    ]
