# Generated by Django 5.0.4 on 2024-05-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='direction',
            table='Directions',
        ),
        migrations.AlterModelTable(
            name='district',
            table='Districts',
        ),
        migrations.AlterModelTable(
            name='post',
            table='Posts',
        ),
        migrations.AlterModelTable(
            name='province',
            table='Provinces',
        ),
        migrations.AlterModelTable(
            name='ward',
            table='Wards',
        ),
    ]
