# Generated by Django 5.0.4 on 2024-05-21 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_posttime'),
        ('users', '0003_alter_role_rolename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='account',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.account'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postTime',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(blank=True),
        ),
    ]
