# Generated by Django 5.0.4 on 2024-05-21 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_account_alter_post_posttime_and_more'),
        ('users', '0004_account_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.account'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postTime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
